# Generated by Django 4.1.2 on 2025-05-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_problem_pdf_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='pdf_url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
