# Generated by Django 5.2.1 on 2025-08-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_problem_pdf_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='view_mode',
            field=models.CharField(blank=True, default='markdown', max_length=10),
        ),
    ]
