# Generated by Django 5.2.1 on 2025-08-05 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_problem_view_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='view_mode',
            field=models.CharField(blank=True, default='plate', max_length=10),
        ),
    ]
